src/Entity/Activity.php
<?php

namespace App\Entity;

use App\Repository\ActivityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;

/**
 * @ORM\Entity(repositoryClass=ActivityRepository::class)
 */
class Activity
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255,minMessage="titre trop court")
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;


    /**
     * @ORM\Column(type="float")
     */
    private $latitude;

    /**
     * @ORM\Column(type="float")
     */
    private $longitude;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="Activity")
     */
    private $Category;
    //to rename categories

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="activity", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $zipcode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street_number;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_indoor;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_outdoor;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $updated_by;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deleted_at;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $animals;
    //rename animalFriendly

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_handicaped;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="activites")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Bookings::class, mappedBy="activity", orphanRemoval=true)
     */
    private $bookings;

    public function __construct()
    {
        $this->Category = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->bookings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }


    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }


    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }
    /**
     * @ORM\PrePersist
     */
    public function setCreatedAt(): self
    {
        $this->createdAt = new \DateTime();

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategory(): Collection
    {
        return $this->Category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->Category->contains($category)) {
            $this->Category[] = $category;
            $category->addActivity($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->Category->contains($category)) {
            $this->Category->removeElement($category);
            $category->removeActivity($this);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setActivity($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getActivity() === $this) {
                $comment->setActivity(null);
            }
        }

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipcode(): ?int
    {
        return $this->zipcode;
    }

    public function setZipcode(int $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getStreetNumber(): ?string
    {
        return $this->street_number;
    }

    public function setStreetNumber(string $street_number): self
    {
        $this->street_number = $street_number;

        return $this;
    }

    public function getIsIndoor(): ?bool
    {
        return $this->is_indoor;
    }

    public function setIsIndoor(bool $is_indoor): self
    {
        $this->is_indoor = $is_indoor;

        return $this;
    }

    public function getIsOutdoor(): ?bool
    {
        return $this->is_outdoor;
    }

    public function setIsOutdoor(bool $is_outdoor): self
    {
        $this->is_outdoor = $is_outdoor;

        return $this;
    }

    public function getUpdatedBy(): ?int
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?int $updated_by): self
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAt(): self
    {
        $this->updated_at = new \Datetime();

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(): self
    {
        $this->deleted_at = new \DateTime();

        return $this;
    }

    public function getAnimals(): ?bool
    {
        return $this->animals;
    }

    public function setAnimals(?bool $animals): self
    {
        $this->animals = $animals;

        return $this;
    }

    public function getIsHandicaped(): ?bool
    {
        return $this->is_handicaped;
    }

    public function setIsHandicaped(?bool $is_handicaped): self
    {
        $this->is_handicaped = $is_handicaped;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Bookings[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Bookings $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setActivity($this);
        }

        return $this;
    }

    public function removeBooking(Bookings $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getActivity() === $this) {
                $booking->setActivity(null);
            }
        }

        return $this;
    }

}

src/Entity/Report.php
<?php

namespace App\Entity;

use App\Repository\ReportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReportRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Report
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Comment::class, inversedBy="reports")
     * @ORM\JoinColumn(nullable=false)
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reports")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=ReportReason::class, inversedBy="reports")
     * @ORM\JoinColumn(nullable=false)
     */
    private $reason;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $moderated_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }
    /**
     * @ORM\PrePersist
     */
    public function setDate(): self
    {
        $this->date = new \DateTime();

        return $this;
    }

    public function getModeratedAt(): ?\DateTimeInterface
    {
        return $this->moderated_at;
    }

    public function setModeratedAt(?\DateTimeInterface $moderated_at): self
    {
        $this->moderated_at = $moderated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    public function getComment(): ?comment
    {
        return $this->comment;
    }

    public function setComment(?comment $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getReason(): ?ReportReason
    {
        return $this->reason;
    }

    public function setReason(?ReportReason $reason): self
    {
        $this->reason = $reason;

        return $this;
    }
}

src/Form/ActivityType.php
<?php

namespace App\Form;

use App\Entity\Activity;
use App\Entity\Category;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\NumberType;




class ActivityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('latitude')
            ->add('longitude')
            ->add('picture', FileType::class, [
                'label'=>'image au format .jpeg',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '4M',
                        'mimeTypes' => [
                            'image/jpeg'
                        ],
                        'mimeTypesMessage' => 'Merci d\'enregistrer une image au format .jpeg',
                    ])
                ],
            ])
            ->add('city')
            ->add('zipcode', NumberType::class)
            ->add('street')
            ->add('street_number')
            ->add('category', EntityType::class, [
                'multiple'=> true,
                'class' => Category::class,
                'choice_label' => 'name',
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('a')
                        ->andWhere('a.deleted_at is NULL');
                },
            ])
            ->add('is_indoor')
            ->add('is_outdoor')
            ->add('animals')
            ->add('is_handicaped')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Activity::class,
        ]);
    }
}

templates/activity/_comment_report_popup.html.twig
<div class="modal fade" id="CommentReportModal" tabindex="-1" role="dialog" aria-labelledby="CommentReportModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="Report Comment">Signaler un commentaire</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times</span>
                </button>
            </div>
            {{form_start(reportForm)}}
            <div class="modal-body">
                {{ form_label(reportForm.reason) }}
                {{ form_widget(reportForm.reason) }}
                {{ form_errors(reportForm.reason) }}
            </div>
            <input type="hidden" name="comment_id" id="comment_id" value="">
            <div class="modal-footer">
                <button type="submit" class="btn btn-success">Signaler</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
            </div>
            {{form_end(reportForm) }}
        </div>
    </div>
</div>

templates/activity/create.html.twig
{%  extends 'base.html.twig' %}
{% form_theme formActivity 'bootstrap_4_layout.html.twig' %}

{% block body %}
	<section>
		<div class="container pb-5">
			<div class="row text-center pt-5 pb-3">
				<div class="col-lg-6 m-auto">
					<h1 class="h1">
						{% if editMode %}
							Modifier Mon Activité
						{% else %}
							Créer Une Activité
						{% endif %}
					</h1>
				</div>
			</div>
			{{ form_start(formActivity) }}

			{{ form_row(formActivity.name, {'label' : 'Nom', 'attr' : {'placeholder' : "Nom", 'title' : 'titre trop court'}}) }}
			{{ form_row(formActivity.description, {'attr' : {'placeholder' : "Description"}}) }}
			{{ form_row(formActivity.latitude, {'attr' : {'placeholder' : "Latitude"}}) }}
			{{ form_row(formActivity.longitude, {'attr' : {'placeholder' : "Longitude"}}) }}
			{{ form_row(formActivity.picture) }}
			{{ form_row(formActivity.category, {'label' : 'Catégories'}) }}
			{{ form_row(formActivity.city, {'label' : 'Ville', 'attr' : {'placeholder' : "Ville"}}) }}
			{{ form_row(formActivity.zipcode, {'label' : 'Code postal', 'attr' : {'placeholder' : "Code postal"}}) }}
			{{ form_row(formActivity.street_number, {'label' : 'Numéro de la rue','attr' : {'placeholder' : "Numéro de rue"}}) }}
			{{ form_row(formActivity.street, {'label' : 'Nom de la rue', 'attr' : {'placeholder' : "Nom de la rue"}}) }}
			<h2 class="h2">Cochez les affirmations qui sont exactes :</h2>
			{{ form_row(formActivity.is_indoor, {'label' : 'Cette activité est pratiquable en intérieur', 'attr' : {'placeholder' : "Indoor"}}) }}
			{{ form_row(formActivity.is_outdoor, {'label' : 'Cette activité est pratiquable en extérieur', 'attr' : {'placeholder' : "Outdoor"}}) }}
			{{ form_row(formActivity.animals, {'label' : 'Les animaux sont les bienvenues', 'attr' : {'placeholder' : "Animaux"}}) }}
			{{ form_row(formActivity.is_handicaped, {'label' : 'Cette activité est accessible aux personnes à mobilité réduite', 'attr' : {'placeholder' : "Accès aux personnes à mobilité réduite"}}) }}
			<button type="submit" class="btn btn-success">
				{% if editMode %}
					Modifier Activité
				{% else %}
					Créer Activité
				{% endif %}
			</button>
			{{ form_end(formActivity) }}
		</div>
	</section>

{% endblock %}

templates/activity/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activités{% endblock %}
{% block head %}
	{{ encore_entry_link_tags('activities') }}
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
	<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
			integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
			crossorigin=""></script>


	<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v1.0.0/MarkerCluster.css' rel='stylesheet' />
	<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v1.0.0/MarkerCluster.Default.css' rel='stylesheet' />
	<script src="https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js"></script>

{% endblock %}


{% block body %}
	<section>
		<div class="container pb-5">
			<div class="row text-center pt-5 pb-3">
				<div class="col-lg-6 m-auto">
					<h1 class="h1">Activités :</h1>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-3">
					<div class="row pt-5">
						<div class="col-lg-12"><h2 class="h2">Catégories</h2></div>
					</div>
					<ul class="list-unstyled">
						<li class="filterGroup">
							<h5 class="h5">Accessibilité : </h5>
							<div class="row justify-content-center">
								<a class="filter constraint unselected services-icon-wap shadow mr-2 pl-1 pt-1 pr-1 pb-1" data-filter="handicaped">
									<i class="fas fa-wheelchair fa-2x"></i>
								</a>
								<a class="filter constraint unselected services-icon-wap shadow mr-2 pl-1 pt-1 pr-1 pb-1" data-filter="animals">
									<i class="fas fa-paw fa-2x"></i>
								</a>
							</div>
						</li>
						<li class="filterGroup">
							<h5 class="h5">Climat : </h5>
							<div class="row justify-content-center">
								<a class="filter constraint unselected services-icon-wap shadow mr-2 pl-1 pt-1 pr-1 pb-1" data-filter="indoor">
									<i class="fas fa-home fa-2x"></i>
								</a>
								<a class="filter constraint unselected services-icon-wap shadow mr-2 pl-1 pt-1 pr-1 pb-1" data-filter="outdoor">
									<i class="fas fa-campground fa-2x"></i>
								</a>
							</div>
						</li>
					</ul>
					<ul class="list-unstyled">
						<h5 class="h5">Catégories : </h5>
						{% for category in categories %}
						<li>
							<a class="filter option unselected text-truncate" data-filter="{{ category.id }}"  title="{{ category.description }}">
								<div class="col-lg-12">
									<div class=" services-icon-wap shadow pl-2 mb-2">
										{{ category.name }}
									</div>
								</div>
							</a>
						</li>


						{% endfor %}
					</ul>
				</div>

				<div class="col-lg-9">
					<ul class="list-unstyled">
						<li class="filterGroup">
							<div class="row justify-content-center">
								<a class="services-icon-wap shadow viewsOptions isList" ><i class="fas fa-list fa-3x"></i></a>
								<a class="services-icon-wap shadow viewsOptions isMap"><i class="fas fa-map-marked-alt fa-3x"></i></a>
							</div>
						</li>
					</ul>
					<div class="activitiesViews displayed" id="mapid"></div>
					<div class="activitiesViews hidden" id="isList">
						<section class="articles row d-flex flex-wrap"></section>
					</div>
				</div>
			</div>

		</div>

	</section>

{% endblock %}
{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('activities') }}
	<script src="https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js"></script>
	<script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v1.0.0/leaflet.markercluster.js'></script>
{% endblock %}

templates/activity/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activitités : {{ activity.name }} {% endblock %}
{% block head %}{{ encore_entry_link_tags('show') }}{% endblock %}

{% block body %}
	<section class="bg-light">
		<div class="container pb-5">
			<div class="row">
				<div class="col-lg-5 mt-5">
					<div class="card mb-3">
						<img class="card-img img-fluid" src="
						{% if activity.picture != "activity_default.jpg" %}
							{{ asset('images/'~ activity.picture) }}" alt="{{ activity.name }}
						{% else %}
							{{ asset('images/activity_default.jpg') }}" alt="image default
						{% endif %}
						" id="product-detail">
					</div>
				</div>
				<div class="col-lg-7 mt-5">
					<div class="card">
						<div class="card-body">
							<p>
							<div class="row justify-content-end">
								<div class="row">
									<div class="col-lg-3"
										 title="{% if activity.isIndoor==1 %}cette activité se pratique en intérieur{% else %}la pratique de cette activité n'est pas possible en intérieur{% endif %}"><span><i class="fas fa-home fa-3x
											{% if activity.isIndoor==1 %}
												appThemeColorOne
											{% else %}
												appThemeColorTwo isUnavailableForThisActivity
											{% endif %}"></i></span>
									</div>
									<div class="col-lg-3"
										 title="{% if activity.isOutdoor==1 %}cette activité se pratique en extérieur{% else %}la pratique de cette activité n'est pas possible en extérieur{% endif %}"
									>
									<span>
										<i class="
											fas fa-campground fa-3x
											{% if activity.isOutdoor==1 %}
												appThemeColorOne
											{% else %}
												appThemeColorTwo isUnavailableForThisActivity
											{% endif %}
										">
										</i>
									</span>
									</div>
									<div class="col-lg-3"
										 title="{% if activity.isHandicaped==1 %}cette activité est accessible aux personnes à mobilité réduite{% else %}la pratique de cette activité n'est pas possible pour les personnes à mobilité réduite{% endif %}"
									>
										<i class="
											fas fa-wheelchair fa-3x
												{% if activity.isHandicaped==1 %}
													appThemeColorOne
												{% else %}
													appThemeColorTwo isUnavailableForThisActivity
												{% endif %}
											">
										</i>
									</div>
									<div class="col-lg-3"
										 title="{% if activity.animals==1 %}nos amis les animaux sont les bienvenus{% else %}nos amis les animaux ne sont pas les bienvenus{% endif %}"
									>
										<i class="
											fas fa-paw fa-3x
											{% if activity.animals==1 %}
												appThemeColorOne
											{% else %}
												appThemeColorTwo isUnavailableForThisActivity
											{% endif %}
										">
										</i>
									</div>
								</div>
							</div>
							</p>
							<h1 class="h2">{{ activity.name }}</h1>
							<h6>Description:</h6>
							<p>{{activity.description | raw}}</p>

							<ul class="list-unstyled pb-3">
								{% if activity.category|length>0 %}
								<div class="row">
									<div class="col-lg-12">
										<div class="row">
											<div class="col-lg-12">
												<h6>Catégorie(s) :</h6>
											</div>
										</div>
										<div class="row">
											{% for category in activity.category %}
												<div class="categories">
													{{category.name }}
												</div>
											{% endfor %}
										</div>
									</div>
								</div>
								{% endif %}
							</ul>
							<p>
								<div class="row">
									<div class="col-lg-12">
										<h6 class="">Adresse :</h6>
									</div>
									<div class="col-lg-12">
										<div class="row">
											<div class="col-lg-12">
												Ville : {{ activity.streetNumber}} {{ activity.street}}, {{activity.city}} ({{ activity.zipcode}})
											</div>
										</div>
										<div class="row">
											<a class="col-lg-6 btn btn-success" role="button"
											   id="toRouteInstructions"
											   href="https://www.google.com/maps/search/?api=1&query={{ activity.latitude }},{{ activity.longitude }}"
											   title="https://www.google.com/maps/search/?api=1&query={{ activity.latitude }},{{ activity.longitude }}"
											   target="_blank"
											>
												<i class="far fa-user fa-2x"></i>
												<i class="fas fa-long-arrow-alt-right fa-2x"></i>
												<i class="fas fa-route fa-2x"></i>
											</a>
										</div>
									</div>
								</div>
							</p>
							<p>
							<div class="row">
								<div class="col-lg-12">
									<h6>Réservation :</h6>
								</div>
								<div class="col-lg-12">
									<div class="row">
										<a role="button" id="toBookingsView" class="col-lg-6 btn btn-success" href="{{ path('bookings_index', {'id' :  activity.id }) }}" title="Réserver une date pour cette activité">
											<i class="fas fa-calendar-alt fa-2x"></i>
										</a>
									</div>
								</div>
							</div>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="container pb-5">
			{% if is_granted('ROLE_USER') %}
				<div class="col-lg-11 mx-auto bg-light" id="commentForm">
					{{form_start(commentForm)}}
					<div class="row">
						<div class="col-lg-12">
							{{ form_label(commentForm.content, "Nouveau Commentaire :", {'attr': {'placeholder' : "Votre commentaire"}}) }}
							{{ form_widget(commentForm.content) }}
						</div>
						<div class="col-lg-12">
							<button type="submit" class="col-lg-12 btn btn-success">
								<i class="fas fa-envelope"></i>
								<span> Commenter</span>
							</button>
						</div>
					</div>
					{{form_end(commentForm)}}
				</div>
			{% else %}
				<div class="row text-center pt-5 pb-3">
					<div class="col-lg-8 m-auto">
						<h2 class="h2">vous devez être connecté pour laisser un commentaire :</h2>
						<p>
							<a class="btn btn-success" href="{{ path('security_login') }}">Connexion</a>
						</p>
					</div>
				</div>
			{% endif %}

			<div class="col-lg-12">
				<h2>{{ activity.comments | length }} Commentaire(s) : </h2>
			</div>

			{% for comment in activity.comments|sort((a, b) => b.createdAt <=> a.createdAt) %}
				{% if comment.deletedAt is null %}
					<div class="col-lg-11 mx-auto comments">
						<div class="row">
							<div class="col-lg-3 appThemeBackgroundColorFive">
								{{ comment.user.username }} (<small>{{ comment.createdAt | date('d/m/Y à H:i') }}</small>)
								<div class="row">
									{%if app.user and app.user.id==comment.user.id%}
										<div class="col-lg-1">
											<a href="{{ path('comment_delete', {'id':comment.id}) }}" title="supprimer le commentaire">
												<i class="fas fa-times-circle"></i>
											</a>
										</div>
									{% endif %}
								</div>
							</div>
							<div class="col-9">
								{{ comment.content | raw }}
								{% if (comment.moderatedAt) is null and (is_granted('ROLE_USER')) %}
									<div class="row justify-content-end">
										<div class="col-lg-1 report">
											<a type="button" class="openReportModal" title="signaler" data-toggle="modal" data-comment-id="{{ comment.id }}" data-target="#CommentReportModal">
												<i class="far fa-flag fa-2x"></i>
											</a>
										</div>
									</div>
								{% endif %}
							</div>
						</div>
					</div>
				{% endif %}
			{% endfor %}
		</div>

		{{ include('/activity/_comment_report_popup.html.twig') }}
	</section>

	{{ encore_entry_script_tags('show') }}
{% endblock %}

templates/activity/test.html.twig
{% extends 'base.html.twig' %}

{% block head %}
  {{ encore_entry_link_tags('test') }}
{% endblock %}
{% block stylesheets %}
  <style>
    #calendar{
     width:80%;
     margin:auto;
    }
  </style>
{% endblock %}
{% block body %}
  <h1>test</h1>
  <div id="calendar"></div>
{% endblock %}
{% block javascripts %}
  {{ encore_entry_script_tags('test') }}


{% endblock%}